-- Request Logs (Existing)
CREATE TABLE IF NOT EXISTS requests (
    id bigint generated by default as identity primary key,
    agent_id text,
    timestamp timestamptz default now(),
    status integer,
    amount text,
    tx_hash text,
    endpoint text,
    error text,
    credit_grade text,
    CONSTRAINT unique_tx_hash UNIQUE (tx_hash) -- Prevent replay attacks
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_requests_tx_hash ON requests(tx_hash) WHERE tx_hash IS NOT NULL;

-- Realtime for Requests (Idempotent fix)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables 
            WHERE pubname = 'supabase_realtime' 
            AND schemaname = 'public' 
            AND tablename = 'requests'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE requests;
        END IF;
    END IF;
END $$;

-- Agent Debts (Existing)
CREATE TABLE IF NOT EXISTS agent_debts (
    agent_id text primary key,
    debt_balance text default '0',
    last_updated timestamptz default now()
);

-- ==============================================================================
-- MULTI-PROVIDER & RBAC SCHEMA
-- ==============================================================================

-- 1. Profiles (Extends auth.users)
-- Links Supabase Auth Users to roles (Admin vs Provider)
CREATE TABLE IF NOT EXISTS profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    role text default 'provider', -- 'admin' or 'provider'
    created_at timestamptz default now()
);

-- 2. Services
-- Registered APIs managed by Providers
CREATE TABLE IF NOT EXISTS services (
    id uuid default gen_random_uuid() primary key,
    provider_id uuid references profiles(id) on delete cascade,
    slug text unique not null,       -- e.g. "my-weather-api" -> /gatekeeper/my-weather-api
    name text not null,
    upstream_url text not null,      -- e.g. https://api.weather.com
    price_wei text default '0',      -- Price per call in Wei
    min_grade text default 'F',      -- A, B, C, D, E, F
    status text default 'pending',   -- pending | verified | rejected
    verification_token text,         -- Random token for domain verification
    verified_at timestamptz,         -- When domain was verified
    created_at timestamptz default now()
);

-- 3. Row Level Security (RLS) Policies

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
-- Users can view their own profile
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

-- Services Policies
-- Everyone (including anon/gateway) can READ services (to resolve routes)
-- UPDATE: Red Team Audit fixed. "Public can read services" is too broad.
-- We must restrict sensitive columns (upstream_url).
-- 
-- STRATEGY:
-- 1. Revoke generic select for anon.
-- 2. Create a "public_services" VIEW that exposes only safe columns.
-- 3. Grant anon access to the View.

-- OLD POLICY (Commented out / Dropped):
DROP POLICY IF EXISTS "Public can read services" ON services;

-- NEW POLICY:
-- Only authenticated providers (for their own data) or Service Role (Backend) can direct select.
-- Actually, the Backend uses Service Key (bypasses RLS) if we configure it right.
-- BUT, if backend uses ANON key, we need a policy.
-- The safest "Hackathon Fix" is to allow SELECT but rely on the backend not to expose it to the frontend.
-- HOWEVER, to fix "Service Enumeration" by a malicious client, we must stop `supabase.from('services').select('*')` from working for anon.

-- So:
-- 1. Create View `public_services` (safe).
-- 2. Grant logic handled below.

CREATE OR REPLACE VIEW public_services AS
SELECT slug, name, price_wei, min_grade
FROM services;

-- Grant access to anon
GRANT SELECT ON public_services TO anon, authenticated;

-- Ensure RLS forbids direct access for Anon to 'services' table
-- (We just dropped the allow policy, so default deny applies, unless another policy fits)
-- "Providers can view own" still works for authenticated.

-- Providers can INSERT their own services
DROP POLICY IF EXISTS "Providers can create services" ON services;
CREATE POLICY "Providers create services" ON services
    FOR INSERT WITH CHECK (auth.uid() = provider_id);

-- Providers can UPDATE their own services
DROP POLICY IF EXISTS "Providers can update own services" ON services;
CREATE POLICY "Providers can update own services" ON services
    FOR UPDATE USING (auth.uid() = provider_id);

-- Providers can DELETE their own services
DROP POLICY IF EXISTS "Providers can delete own services" ON services;
CREATE POLICY "Providers can delete own services" ON services
    FOR DELETE USING (auth.uid() = provider_id);

-- 4. Trigger to auto-create Profile on Signup
-- (Standard Supabase Pattern)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'provider'); -- Default to provider
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid error on rerun
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 8. Provider Settings (Settlements)
CREATE TABLE IF NOT EXISTS provider_settings (
    provider_id uuid primary key references profiles(id) on delete cascade,
    withdrawal_address text,         -- Wallet address to receive funds
    auto_withdraw_enabled boolean default false,
    min_withdrawal_amount text default '1000000000000000000', -- Default 1 CRO (in Wei)
    updated_at timestamptz default now()
);

-- 9. Withdrawals History
CREATE TABLE IF NOT EXISTS withdrawals (
    id uuid default gen_random_uuid() primary key,
    provider_id uuid references profiles(id) on delete cascade,
    amount_wei text not null,
    to_address text not null,
    tx_hash text,
    status text default 'pending', -- pending | completed | failed
    created_at timestamptz default now()
);

-- RLS for Settings
ALTER TABLE provider_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE withdrawals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own settings" ON provider_settings;
CREATE POLICY "Users can manage own settings" ON provider_settings
    USING (auth.uid() = provider_id)
    WITH CHECK (auth.uid() = provider_id);

DROP POLICY IF EXISTS "Users can view own withdrawals" ON withdrawals;
CREATE POLICY "Users can view own withdrawals" ON withdrawals
    FOR SELECT USING (auth.uid() = provider_id);
